### ISSUE TITLE
Button can't be used as a simple a tag for hrefs

### ISSUE THREAD

**Issue by allanhortle** [bigdatr/stampy#78]

**Comment by dxinteractive** [comment]
`<button>` tags don't accepts hrefs and aren't meant to be links, although I get that we'll often need links that look like `Button`. Should this internally create a `<a>` instead of a `<button>` if an `href` prop is provided? And then you can't have a natively `disabled` `<a>` so it's all a bit weird?

**Comment by dxinteractive** [comment]
A goose `Link` does this for us now.
